/**
 * monitoring_nav2_main.cpp
 *
 * Thin runner for the Nav2 monitoring behavior tree.
 * Loads plugin shared libraries, builds the blackboard, creates the tree
 * from XML, and ticks at 10 Hz. Plugin implementations live in plugins/.
 *
 * Namespace support:
 *   Pass ROS parameter  nav2_namespace:=<ns>  (e.g. nav2_namespace:=apple)
 *
 * Tree structure (mirrors follow_point.xml):
 *   PipelineSequence
 *   ├── ControllerSelector  → /<ns>/controller_selector
 *   ├── PlannerSelector     → /<ns>/planner_selector
 *   ├── RateController hz=1.0
 *   │   └── Sequence
 *   │       ├── GoalUpdater               → /<ns>/goal_update
 *   │       │   └── ComputePathToPose     → /<ns>/compute_path_to_pose/_action/status
 *   │       └── TruncatePath
 *   └── KeepRunningUntilFailure
 *       └── FollowPath                    → /<ns>/follow_path/_action/status
 */

#include <sstream>
#include <string>
#include "rclcpp/rclcpp.hpp"
#include "ament_index_cpp/get_package_prefix.hpp"
#include "ament_index_cpp/get_package_share_directory.hpp"
#include "behaviortree_cpp_v3/bt_factory.h"
#include "behaviortree_cpp_v3/loggers/bt_zmq_publisher.h"
#include "behaviortree_cpp_v3/loggers/bt_file_logger.h"
#include "plugins_list.hpp"   // CMake-generated: BT_BUILTIN_PLUGINS

// Plugin registration symbols — each shared lib exposes BT_REGISTER_NODES.
// The list of libraries comes from plugins_list.hpp (generated by CMake from
// the plugin_libs variable in CMakeLists.txt) — no hardcoded names here.

int main(int argc, char ** argv)
{
  rclcpp::init(argc, argv);

  auto node = rclcpp::Node::make_shared("nav2_bt_monitor");
  node->declare_parameter("nav2_namespace",    std::string(""));
  node->declare_parameter("zmq_publisher_port", 1669);
  node->declare_parameter("zmq_server_port",    1670);

  const std::string ns      = node->get_parameter("nav2_namespace").as_string();
  const int zmq_pub_port    = node->get_parameter("zmq_publisher_port").as_int();
  const int zmq_srv_port    = node->get_parameter("zmq_server_port").as_int();

  RCLCPP_INFO(node->get_logger(), "Nav2 BT Monitor — namespace: '%s'", ns.c_str());

  // Build blackboard — plugins read node + namespace from here.
  auto blackboard = BT::Blackboard::create();
  blackboard->set("node",           node);
  blackboard->set("nav2_namespace", ns);

  BT::BehaviorTreeFactory factory;

  // Load every plugin listed in plugins_list.hpp (generated by CMake from
  // the plugin_libs variable in CMakeLists.txt).
  // Libraries are installed to <prefix>/lib/ — full path avoids LD_LIBRARY_PATH.
  const std::string pkg_prefix = ament_index_cpp::get_package_prefix("nav2_monitoring_tree");
  std::istringstream ss(nav2_monitoring_tree::BT_BUILTIN_PLUGINS);
  for (std::string lib; std::getline(ss, lib, ';'); ) {
    if (lib.empty()) {continue;}
    const std::string so_path = pkg_prefix + "/lib/lib" + lib + ".so";
    RCLCPP_DEBUG(node->get_logger(), "Loading plugin: %s", so_path.c_str());
    factory.registerFromPlugin(so_path);
  }

  const std::string pkg_share = ament_index_cpp::get_package_share_directory("nav2_monitoring_tree");
  const std::string tree_xml  = pkg_share + "/config/nav2_monitor_tree.xml";
  auto tree = factory.createTreeFromFile(tree_xml, blackboard);

  const std::string log_path = pkg_share + "/config/nav2_bt_log.fbl";
  BT::FileLogger file_logger(tree, log_path.c_str());

  // ZMQ publisher — connect Groot in Real-time mode.
  // Uses ports 1669/1670 so they don't clash with turtle_bt (1666/1667).
  BT::PublisherZMQ zmq_publisher(tree, 25, zmq_pub_port, zmq_srv_port);

  RCLCPP_INFO(node->get_logger(),
    "Tree loaded. Open Groot → Real-time on publisher port %d / server port %d. Ticking at 10 Hz.",
    zmq_pub_port, zmq_srv_port);

  rclcpp::Rate rate(10);
  while (rclcpp::ok()) {
    tree.tickRoot();
    rclcpp::spin_some(node);
    rate.sleep();
  }

  rclcpp::shutdown();
  return 0;
}
